<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistElixirDogmaLinter' => 'src/lint/linter/ArcanistElixirDogmaLinter.php',
    'ExunitTestEngine' => 'src/unit/engine/ExunitTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistElixirDogmaLinter' => 'ArcanistExternalLinter',
    'ExunitTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
